using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ScratchpadSharp.Core.Database;

public static class EfScaffoldGenerator
{
    public static string GenerateModel(DbSchemaSnapshot snapshot, DatabaseProviderInfo provider,
        string namespaceSegment, string connectionString, IEnumerable<string>? tableNames = null)
    {
        var filter = tableNames?.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var tables = snapshot.Tables
            .Where(ShouldScaffoldTable)
            .Where(t => filter == null || filter.Contains(t.Name))
            .Where(HasPrimaryKey)
            .ToList();

        if (tables.Count == 0)
            return "// No tables to scaffold.";

        var escapedCs = EscapeCSharpString(connectionString);
        var useMethod = string.IsNullOrEmpty(provider.UseExtensionMethod)
            ? "UseSqlite"
            : provider.UseExtensionMethod;
        var ns = $"Modules.{namespaceSegment}";

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ScratchpadSharp EF Core module");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        foreach (var table in tables)
        {
            var className = ToPascalIdentifier(table.Name);
            sb.AppendLine($"public class {className}");
            sb.AppendLine("{");
            foreach (var col in table.Columns)
            {
                var propType = MapClrType(col.DataType, col.IsNullable);
                var propName = ToPascalIdentifier(col.Name);
                sb.AppendLine($"    public {propType} {propName} {{ get; set; }}");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public class AppDbContext : DbContext");
        sb.AppendLine("{");
        foreach (var table in tables)
        {
            var className = ToPascalIdentifier(table.Name);
            sb.AppendLine($"    public DbSet<{className}> {className}s => Set<{className}>();");
        }

        sb.AppendLine();
        sb.AppendLine("    protected override void OnConfiguring(DbContextOptionsBuilder options)");
        sb.AppendLine($"        => options.{useMethod}(\"{escapedCs}\");");
        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        foreach (var table in tables)
        {
            var className = ToPascalIdentifier(table.Name);
            sb.AppendLine($"        modelBuilder.Entity<{className}>(entity =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            entity.ToTable({FormatToTableArgs(table)});");

            var pkProps = table.Columns
                .Where(c => c.IsPrimaryKey)
                .OrderBy(c => c.Ordinal)
                .Select(c => ToPascalIdentifier(c.Name))
                .ToList();

            if (pkProps.Count == 1)
                sb.AppendLine($"            entity.HasKey(e => e.{pkProps[0]});");
            else
                sb.AppendLine(
                    $"            entity.HasKey(e => new {{ {string.Join(", ", pkProps.Select(p => $"e.{p}"))} }});");

            foreach (var col in table.Columns)
            {
                var propName = ToPascalIdentifier(col.Name);
                if (!string.Equals(propName, col.Name, StringComparison.Ordinal))
                    sb.AppendLine(
                        $"            entity.Property(e => e.{propName}).HasColumnName(\"{EscapeCSharpString(col.Name)}\");");
            }

            sb.AppendLine("        });");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// EF defaults the table name to the DbSet property (often pluralized); always map to the real schema table.
    /// </summary>
    private static string FormatToTableArgs(DbTableInfo table)
    {
        var name = $"\"{EscapeCSharpString(table.Name)}\"";
        if (string.IsNullOrWhiteSpace(table.Schema) ||
            table.Schema.Equals("main", StringComparison.OrdinalIgnoreCase))
            return name;

        return $"{name}, \"{EscapeCSharpString(table.Schema)}\"";
    }

    /// <summary>Skips EF/system tables that should not become mapped entities.</summary>
    public static bool ShouldScaffoldTable(DbTableInfo table)
    {
        if (table.IsView)
            return false;

        var name = table.Name;
        if (name.StartsWith("__", StringComparison.Ordinal))
            return false;

        if (name.StartsWith("sqlite_", StringComparison.OrdinalIgnoreCase))
            return false;

        return true;
    }

    private static bool HasPrimaryKey(DbTableInfo table) =>
        table.Columns.Any(c => c.IsPrimaryKey);

    public static string ToPascalIdentifier(string name)
    {
        var cleaned = Regex.Replace(name ?? string.Empty, @"[^\w]+", "_");
        if (string.IsNullOrEmpty(cleaned))
            return "Entity";

        var parts = cleaned.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var pascal = string.Concat(parts.Select(p =>
            char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : string.Empty)));

        if (string.IsNullOrEmpty(pascal))
            return "Entity";
        if (char.IsDigit(pascal[0]))
            return "T" + pascal;
        return pascal;
    }

    public static string MapClrType(string sqlType, bool isNullable)
    {
        var t = (sqlType ?? "").Trim().ToLowerInvariant();
        var baseType = t;
        var paren = t.IndexOf('(');
        if (paren >= 0)
            baseType = t[..paren];

        string clr = baseType switch
        {
            "int" or "integer" or "mediumint" or "smallint" or "tinyint" => "int",
            "bigint" => "long",
            "real" or "float" or "double" or "double precision" => "double",
            "numeric" or "decimal" or "money" or "smallmoney" => "decimal",
            "bit" or "boolean" or "bool" => "bool",
            "uniqueidentifier" or "uuid" or "guid" => "Guid",
            "datetime" or "datetime2" or "smalldatetime" or "date" or "timestamp" => "DateTime",
            "datetimeoffset" => "DateTimeOffset",
            "time" => "TimeSpan",
            "blob" or "image" or "varbinary" or "binary" or "rowversion" => "byte[]",
            "text" or "ntext" or "varchar" or "nvarchar" or "char" or "nchar" or "clob" or "xml" or "string" =>
                "string",
            _ => "string"
        };

        if (clr is "string" or "byte[]")
            return isNullable ? clr + "?" : clr;

        return isNullable ? clr + "?" : clr;
    }

    public static string EscapeCSharpString(string value) =>
        (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

    public static bool TryReplaceBakedConnectionString(
        string source, string originalConnectionString, string replacementConnectionString, out string updated)
    {
        updated = source;
        if (string.IsNullOrEmpty(source) ||
            string.Equals(originalConnectionString, replacementConnectionString, StringComparison.Ordinal))
            return true;

        var from = $"\"{EscapeCSharpString(originalConnectionString)}\"";
        var to = $"\"{EscapeCSharpString(replacementConnectionString)}\"";
        if (!source.Contains(from, StringComparison.Ordinal))
            return false;

        updated = source.Replace(from, to, StringComparison.Ordinal);
        return true;
    }
}
