using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ScratchpadSharp.Core.Database;

public static class EfScaffoldGenerator
{
    public static string Generate(DbSchemaSnapshot snapshot, DatabaseProviderInfo provider,
        IEnumerable<string>? tableNames = null)
    {
        var filter = tableNames?.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var tables = snapshot.Tables
            .Where(t => !t.IsView)
            .Where(t => filter == null || filter.Contains(t.Name))
            .ToList();

        if (tables.Count == 0)
            return "// No tables to scaffold.";

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ScratchpadSharp Database explorer");
        sb.AppendLine();

        foreach (var table in tables)
        {
            var className = ToPascalIdentifier(table.Name);
            sb.AppendLine($"public class {className}");
            sb.AppendLine("{");
            foreach (var col in table.Columns)
            {
                var propType = MapClrType(col.DataType, col.IsNullable);
                var propName = ToPascalIdentifier(col.Name);
                if (col.IsPrimaryKey)
                    sb.AppendLine("    // PK");
                sb.AppendLine($"    public {propType} {propName} {{ get; set; }}");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public class AppDbContext : DbContext");
        sb.AppendLine("{");
        foreach (var table in tables)
        {
            var className = ToPascalIdentifier(table.Name);
            sb.AppendLine($"    public DbSet<{className}> {className}s => Set<{className}>();");
        }

        sb.AppendLine();
        sb.AppendLine("    protected override void OnConfiguring(DbContextOptionsBuilder options)");
        var useMethod = string.IsNullOrEmpty(provider.UseExtensionMethod)
            ? "UseSqlite"
            : provider.UseExtensionMethod;
        sb.AppendLine($"        => options.{useMethod}(ConnectionString);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("await using var db = new AppDbContext();");
        var first = ToPascalIdentifier(tables[0].Name);
        sb.AppendLine($"db.{first}s.Take(20).ToList().Dump(\"{first}s\");");

        return sb.ToString();
    }

    public static string ToPascalIdentifier(string name)
    {
        var cleaned = Regex.Replace(name ?? string.Empty, @"[^\w]+", "_");
        if (string.IsNullOrEmpty(cleaned))
            return "Entity";

        var parts = cleaned.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var pascal = string.Concat(parts.Select(p =>
            char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : string.Empty)));

        if (string.IsNullOrEmpty(pascal))
            return "Entity";
        if (char.IsDigit(pascal[0]))
            return "T" + pascal;
        return pascal;
    }

    public static string MapClrType(string sqlType, bool isNullable)
    {
        var t = (sqlType ?? "").Trim().ToLowerInvariant();
        var baseType = t;
        var paren = t.IndexOf('(');
        if (paren >= 0)
            baseType = t[..paren];

        string clr = baseType switch
        {
            "int" or "integer" or "mediumint" or "smallint" or "tinyint" => "int",
            "bigint" => "long",
            "real" or "float" or "double" or "double precision" => "double",
            "numeric" or "decimal" or "money" or "smallmoney" => "decimal",
            "bit" or "boolean" or "bool" => "bool",
            "uniqueidentifier" or "uuid" or "guid" => "Guid",
            "datetime" or "datetime2" or "smalldatetime" or "date" or "timestamp" => "DateTime",
            "datetimeoffset" => "DateTimeOffset",
            "time" => "TimeSpan",
            "blob" or "image" or "varbinary" or "binary" or "rowversion" => "byte[]",
            "text" or "ntext" or "varchar" or "nvarchar" or "char" or "nchar" or "clob" or "xml" or "string" =>
                "string",
            _ => "string"
        };

        if (clr is "string" or "byte[]")
            return isNullable ? clr + "?" : clr;

        return isNullable ? clr + "?" : clr;
    }
}
